### ISSUE TITLE
ofxSQLite vs ofxSQLiteCpp

### ISSUE THREAD

**Issue by wasawi** [bakercp/ofxSQLiteCpp#1] opened 2014-05-26 17:58 UTC
I'm about to start something and i need some DDBB easy, and fast to use.
Is this one better that roxlu's ofxSQLite?
Did you have a better experience with it?

BTW i couldnt run roxlu's ofxSQLite in of0.8. I saw a bunch of commits in your fork so i guess is not well maintained? I didnt try your fork yet.. I will try this one instead that seems more up to date.. but still would be nice to know from you what is best to use..

Thanks in advance for the addon!

**Comment by bakercp** [comment] 2014-05-26 18:51
SQLiteCpp doesn't have some of the memory leaks that ofxSQLite had when I used it.  Ultimately, ofxSQLiteCpp is not much -- just a few examples with using SQLiteCpp, which is very solid.  I'd recommend it. :)

**Comment by wasawi** [comment] 2014-05-26 19:27
Thanks that is convincing enough :)  
I will try it now. I just need something simple so i guess this one will do :+1:

**Comment by dimitre** [comment] 2015-05-07 23:48
I'm trying to use it and it returns me json/json.h file not found. Any ideas of what is missing? thanks!

**Comment by bakercp** [comment] 2015-05-08 00:01
Ah, I recently added ofxJSON as a dependency.

https://github.com/bakercp/ofxSQLiteCpp/blob/master/addon_config.mk

https://github.com/jefftimesten/ofxJSON

If you don't want to use it, just remove the utils files here: 

https://github.com/bakercp/ofxSQLiteCpp/tree/master/src

Basically it's a utility for getting sqlite results as json ...

**Comment by dimitre** [comment] 2015-05-08 14:29
Thank you @bakercp ready to go

**Comment by dimitre** [comment] 2015-05-20 13:46
Thats a great addon, thank you @bakercp
One question: if I want to read periodically from a database, lets say each 2 seconds, is it better to open the database each time or just open once in setup? if it is the second option, how can I do this? Thanks.

**Comment by bakercp** [comment] 2015-05-21 20:40
Hi @dimitre -- it's pretty quick to open and close.  The really nice (and sometimes challenging) thing about SQLiteCPP is that it enforces RAII, so that there is never a chance that a connection will be left open etc.  It's a really nice way to use sqlite once you get used to it.  I think if you are only opening the DB every 2 seconds, I'd just open a new connection with a local variable.  Ultimately you'll just have to profile it and see if it is too slow.  If you want to only have one connection open, you can construct a database member variable in your ofApp constructor (you'll have to define a constructor and construct the database instance in an initialization list ... which can be problematic because sometimes the `ofToDataPath` variables are sometimes not set up that early) -- OR you can create a pointer (or even better a smart / shared pointer) and initialize it in the setup method.

e.g.

```
// ofApp.h
std::shared_ptr<SQLite::Database> db;
```

```
// ofApp.cpp setup()

db = std::shared_ptr<SQLite::Database>(new SQLite::Database(yourFileName));
```

Just be careful with that method because sqlitecpp is not configured to allow multiple threads to use the same connection.

**Comment by bakercp** [comment] 2015-05-21 20:41
Just for reference, I use it both ways using a different connection for each thread and it works nicely.

**Comment by dimitre** [comment] 2015-05-21 20:52
Amazing @bakercp thank you!

**Comment by moebiussurfing** [comment] 2015-07-21 21:00
Hi, I am just trying it and I am having this errors when compiling the example:

![captura de pantalla 2015-07-21 a las 17 58 53](https://cloud.githubusercontent.com/assets/2106149/8812407/4053d4ae-2fd2-11e5-8249-9b820f2861ab.png)

I just created a new project with PG (0.8.4) as usual with the this addon and ofxJSON, and placed de DB file in /data.

**Comment by bakercp** [comment] 2015-07-22 01:46
@moebiussurfing what example files are you trying?  It kind of sounds like you don't have the right includes in the source ... ? (e.g. `#include "SQLiteCpp.h"`) ...

**Comment by moebiussurfing** [comment] 2015-07-23 02:21
@bakercp I am tryng the 'https://github.com/bakercp/ofxSQLiteCpp/tree/master/example'.
I have the '#include "SQLiteCpp.h"' on the ofApp.h like usual...

**Comment by bakercp** [comment] 2015-07-23 02:25
Could you post some code?  It looks like there might be a missing semi colon or something?  Sorry, it's difficult to tell from your error message.  I just created a project for the example and it ran ...

**Comment by moebiussurfing** [comment] 2015-07-23 02:25
![captura de pantalla 2015-07-22 a las 23 25 01](https://cloud.githubusercontent.com/assets/2106149/8841817/ed9d0c38-30c8-11e5-84f6-07ec3a7baf55.png)

**Comment by moebiussurfing** [comment] 2015-07-23 02:26
![captura de pantalla 2015-07-22 a las 23 26 14](https://cloud.githubusercontent.com/assets/2106149/8841833/18c0f19a-30c9-11e5-9e61-0eef1c679394.png)

**Comment by moebiussurfing** [comment] 2015-07-23 02:27
thanks a lot man! super fast reply! :)

**Comment by bakercp** [comment] 2015-07-23 02:28
Those are all errors in the third party library which makes me thing that the headers / implementation files are not being added correctly ... could you make sure all of the header search paths were added by the project generator?  Also, does it work if you use the makefiles or generate a project file for the existing examples?

**Comment by moebiussurfing** [comment] 2015-07-23 02:32
I think I used the porject generator picking the 2 addons (SQLite+JSON) but go make it again now. Also with another of the examples.
What that means: "use the makefiles or generate a project file for the existing examples" ?

**Comment by bakercp** [comment] 2015-07-23 02:34
You can also compile projects without the project generator or xcode by using the make build system.  Just navigate to the example folder you want in the terminal and run `make`.

**Comment by moebiussurfing** [comment] 2015-07-23 02:46
I tryed both ways (Xcode + terminal) and I have the same errors.. but i can see something strange when compiling with make. It says something about "3dPrimitives" example (?)... Could be my PG corrupted? 

sudo make
Password:
Compiling OF library for Release
Compiling ../../../libs/openFrameworks/3d/of3dPrimitives.cpp
c++ -Os -stdlib=libstdc++ -Wall -fexceptions -march=native -mtune=native -finline-functions -arch i386 -fpascal-strings -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks -mmacosx-version-min= -fasm-blocks -funroll-loops -mssse3 -fmessage-length=0 -D__MACOSX_CORE__ -I../../../libs/FreeImage/include -I../../../libs/cairo/include -I../../../libs/cairo/include/cairo -I../../../libs/cairo/include/libpng15 -I../../../libs/cairo/include/pixman-1 -I../../../libs/fmodex/include -I../../../libs/freetype/include -I../../../libs/freetype/include/freetype2 -I../../../libs/freetype/include/freetype2/freetype -I../../../libs/freetype/include/freetype2/freetype/config -I../../../libs/freetype/include/freetype2/freetype/internal -I../../../libs/freetype/include/freetype2/freetype/internal/services -I../../../libs/glew/include -I../../../libs/glew/include/GL -I../../../libs/glfw/include -I../../../libs/glfw/include/GLFW -I../../../libs/glut/include -I../../../libs/openssl/include -I../../../libs/openssl/include/openssl -I../../../libs/poco/include -I../../../libs/rtAudio/include -I../../../libs/tess2/include -I../../../libs/openFrameworks -I../../../libs/openFrameworks/3d -I../../../libs/openFrameworks/app -I../../../libs/openFrameworks/communication -I../../../libs/openFrameworks/events -I../../../libs/openFrameworks/gl -I../../../libs/openFrameworks/graphics -I../../../libs/openFrameworks/math -I../../../libs/openFrameworks/sound -I../../../libs/openFrameworks/types -I../../../libs/openFrameworks/utils -I../../../libs/openFrameworks/video -x objective-c++ -MMD -MP -MF ../../../libs/openFrameworksCompiled/lib/osx/obj/Release/libs/openFrameworks/3d/of3dPrimitives.d -MT../../../libs/openFrameworksCompiled/lib/osx/obj/Release/libs/openFrameworks/3d/of3dPrimitives.o -o ../../../libs/openFrameworksCompiled/lib/osx/obj/Release/libs/openFrameworks/3d/of3dPrimitives.o -c ../../../libs/openFrameworks/3d/of3dPrimitives.cpp
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk'
clang: error: invalid version number in '-mmacosx-version-min='
clang: warning: optimization flag '-finline-functions' is not supported
make[2]: **\* [../../../libs/openFrameworksCompiled/lib/osx/obj/Release/libs/openFrameworks/3d/of3dPrimitives.o] Error 1
make[1]: **\* [Release] Error 2
make: **\* [Release] Error 2

**Comment by moebiussurfing** [comment] 2015-07-23 02:48
config.make looks all commented

**Comment by bakercp** [comment] 2015-07-23 02:48
Hm.  I think that's a different issue -- sounds like your xcode command line tools aren't compatible with the makefiles in 0.8.4.  Have you considered trying this with the master branch (0.9.0).  It's working pretty well these days ...

**Comment by moebiussurfing** [comment] 2015-07-23 02:53
I am a little scared of being updated because sometimes my projects (RPi too) stops working... but I could try.
Do you know if i can go back to a previous command line tools? (I have last Xcode 6.3.2 and 10.10.4. up to date too by mistake haha)

**Comment by moebiussurfing** [comment] 2015-07-23 02:54
Thanks a lot for your replies!!

**Comment by bakercp** [comment] 2015-07-23 03:01
Hm.  Actually, if you're on OSX / 0.8.4, I'd recommend avoiding the project generator for the moment and using OFPlugin to add the addons.  If I recall, there were some bugs in the PG in 0.8.4 ... and OFPlugin (https://github.com/admsyn/OFPlugin) seems to work consistently in 0.8.4.

**Comment by moebiussurfing** [comment] 2015-07-23 03:22
.... I just duplicated the emptyExample and added the 2 addons with OFPlugin but i get the same error. sorry for burning you. I'll make a try to the OF 0.9 and I'll try to stuck here and to not update OS or Xcode again.

**Comment by moebiussurfing** [comment] 2015-07-23 06:10
I can confirm the example is working fine on the master branch now. 

BTW I tried to install an older version of command line tools to keep using the 0.8.4 version, but is not appearing on the Xcode prefs to switch to it. So it seems a little tricky to do it, unless renaming the Xcode.app and installing another older Xcode like 6.1.1. etc.

**Comment by bakercp** [comment] 2016-04-12 16:20
Looks l like things are working.  Closing this.

**Closed as completed by bakercp** 2016-04-12 16:20 UTC
